### ISSUE TITLE
asking for advice

### ISSUE THREAD

**Issue by slimak2** [davechurchill/commandcenter#67]
Hello and Happy holidays to everyone.
This is not issue, i  would just like to ask you for advice.
I want to use this CommandCenter for deep learning research, and i want to train neural network for commanding squad of units in battle. I would like to ask you if i need to use some framework for this, and if you know about some helpful programs that i could use.
I would also like to ask you for any general or specific advices, you could give me about this.

Marry Christmas and Happy New Year.

**Comment by davechurchill** [comment]
I suggest using the Google python ML library for this

**Comment by slimak2** [comment]
but, CommandCenter is in C++ , wouldn't that be a problem? I am sorry if this is a stupid question, i am new in this things.

**Comment by davechurchill** [comment]
It is, but it's also not set up to do machine learning in any convenient way. So if you are set on using ML (for now) you'd probably want to use the pysc2 library instead of commandcenter, until you get more familiar with how to do that within command center - because there is no easy way to do it.

**Comment by alkurbatov** [comment]
Unfortunately I know little about AI but I strongly recommend you to start from Python and something like pysc2. The Python community has a lot of neat frameworks that really simplify all these operations with vectors and matrixes. Even sone well known learning models can be created by handful lines of code.
On the other hand C++ is still great but leaves a lot of routine jobs to be done thus much time will be spent on creation of proper instruments instead of playing with AI models.
