### ISSUE TITLE
Bug with CatalystLE: unable to find all base locations

### ISSUE THREAD

**Issue by janemrich** [davechurchill/commandcenter#70]
The bot is only able to find 12 of the 14 base locations on CatalystLE. Due to this error, it is unable to find its start location. Its start location is thus null and the bot chrashes later.
edit: i got similar issues on other new maps of ladder 2018 Season 1

**Comment by NiksonBinsk** [comment]
I have this problem on each other maps.

**Comment by davechurchill** [comment]
Thanks for letting me know. The base location calculation relies on a distance for clustering resources, this can be tweaked here:

https://github.com/davechurchill/commandcenter/blob/master/src/BaseLocationManager.cpp#L20

However right now it's using air distance instead of ground distance, so making it too big will cause some locations on some maps to include minerals that it shouldn't. I can't remember why I don't currently use ground distance, probably because it was a little slow at the time of writing. 

If you play around with that number (currently 12 build tiles) you can get better results on some maps

**Comment by janemrich** [comment]
Thank you for this information. Fortunatly the other maps are enough for my needs

**Comment by Archiatrus** [comment]
This is most likely due to UnitType::isMineral() is not including all types of minerals/gases. CommandCenter can not find the base locations since it can not find any minerals on the map. See [here](https://github.com/Archiatrus/commandcenter/blob/sc2AILadder/src/UnitType.cpp#L129) my fixed isMineral().

I can make a pull request for this, if it is wanted.
