### ISSUE TITLE
How do I play against my own AI ?

### ISSUE THREAD

**Issue by mecharos** [davechurchill/commandcenter#78]
This is not exactly an issue. I'm finally midway finishing my AI. By somehow follow UAlbertaBot wiki as suggested on the bottom page.
And I want to test it, not against SC2 Computer / BOT. but, against a player (Non-AI) or at least I can test the AI my self.
So, is there any documentation on what to do? or something to change on the code side.
if there is one already and I'm somehow missing it, I'm sorry. 

And Thank you in advance.

**Comment by Archiatrus** [comment]
You do it by adding an empty bot as player 1. You probably already noticed that mouse/keyboard inputs are not disabled while your bot plays. You can see an example [here](https://github.com/Blizzard/s2client-api/blob/master/examples/bot_mp.cc). It is not difficult.

One warning, though. You probably want to play on realtime = true. The problem is that then the bot sometimes behaves unexpected. Actions sometimes get executed late or never. You can try to mitigate this by using realtime = false and a sc2::sleepFor so that each onStep only ends 1/22.4 seconds after the last onStep finished. But then the game feels a bit sluggish for the human.

Other hints you might or might not know: alt+enter for fullscreen. For special hotkeys put the hotkey file in "Documents\StarCraft II\Hotkeys\". For faster question answers join the [sc2ai discord](https://discord.gg/qTZ65sh) ;)

**Comment by davechurchill** [comment]
Thank you for responding!
